version: '3'
services:

  java-api:
    image: ghcr.io/zurnov/java-app-bitcoin:latest
    ports:
     - "8000:8000"
    depends_on:
      - database
    environment:
      API_TOKEN: ${API_TOKEN}
      RPC_USER: ${RPC_USER}
      RPC_PASSWORD: ${RPC_PASSWORD}
      RPC_ADDRESS: ${RPC_ADDRESS}

  database:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: bitcoin_insights_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: