version: '3'
services:
  database:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_DB=bitcoin_insights_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - bitcoin-insights-network

  java-api:
    image: ghcr.io/zurnov/java-app-bitcoin:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
      - RPC_ADDRESS=${RPC_ADDRESS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - bitcoin-insights-network

volumes:
  data:

networks:
  bitcoin-insights-network:
    driver: bridge
